[[questions]]
question = " What is the name of the Python package manager "
answer = "pip"
alts = [
    "pyp",
    "pypm",
    "pypm",
]


[[questions]]
question = " When does __name__ == '__main__' equal True in a Python file "
answer = "When the file is run as a script"
alts = [
    "When the file is imported as a module",
    "When the file has a valid name",
    "When the file only has one function",
]

[[questions]]
question = " Which version of Python is the first with TOML support built in "
answer = "3.11"
alts = [
    "3.9",
    "3.10",
    "3.12",
]